import { Agent, ActivityEntry, Task, UsageData } from "./types";

export const agents: Agent[] = [
  {
    id: "nyx",
    name: "NYX",
    emoji: "\u{1F30C}",
    status: "active",
    role: "Guild Master",
    description:
      "Orchestrator agent. Manages task delegation, monitors agent health, and coordinates guild operations. Named after the goddess of night.",
    machine: "mac-studio-m2",
    currentTask: "Coordinating daily agent briefing",
    lastActivity: "2 minutes ago",
    skills: [
      "Task Orchestration",
      "Agent Monitoring",
      "Priority Management",
      "Error Recovery",
      "Report Generation",
    ],
    color: "#7c3aed",
    accentColor: "#a78bfa",
  },
  {
    id: "hemera",
    name: "HEMERA",
    emoji: "\u{2600}\uFE0F",
    status: "active",
    role: "Outreach Specialist",
    description:
      "Handles external communications, outreach campaigns, and relationship management. Named after the goddess of day.",
    machine: "mac-studio-m2",
    currentTask: "Processing outreach queue — batch 14",
    lastActivity: "30 seconds ago",
    skills: [
      "Email Outreach",
      "Lead Research",
      "CRM Management",
      "Template Generation",
      "Follow-up Scheduling",
    ],
    color: "#d97706",
    accentColor: "#fbbf24",
  },
];

export const activityFeed: ActivityEntry[] = [
  {
    id: "a1",
    agentId: "hemera",
    agentName: "HEMERA",
    agentEmoji: "\u{2600}\uFE0F",
    action: "Completed outreach batch",
    detail: "Sent 23 personalized emails to Series A founders. 4 bounced, 19 delivered.",
    timestamp: "2025-02-26T14:32:00Z",
    type: "task",
  },
  {
    id: "a2",
    agentId: "nyx",
    agentName: "NYX",
    agentEmoji: "\u{1F30C}",
    action: "Reassigned task priority",
    detail: 'Moved "Investor deck review" from low to high priority based on calendar analysis.',
    timestamp: "2025-02-26T14:28:00Z",
    type: "system",
  },
  {
    id: "a3",
    agentId: "hemera",
    agentName: "HEMERA",
    agentEmoji: "\u{2600}\uFE0F",
    action: "Started outreach batch 14",
    detail: "Loading 30 leads from enrichment pipeline. Personalizing templates.",
    timestamp: "2025-02-26T14:15:00Z",
    type: "task",
  },
  {
    id: "a4",
    agentId: "nyx",
    agentName: "NYX",
    agentEmoji: "\u{1F30C}",
    action: "Health check passed",
    detail: "All agents responding. HEMERA latency: 42ms. Memory usage nominal.",
    timestamp: "2025-02-26T14:00:00Z",
    type: "system",
  },
  {
    id: "a5",
    agentId: "nyx",
    agentName: "NYX",
    agentEmoji: "\u{1F30C}",
    action: "Generated daily briefing",
    detail: "Summary: 47 tasks completed yesterday, 12 pending. HEMERA outreach rate: 94% delivery.",
    timestamp: "2025-02-26T13:45:00Z",
    type: "communication",
  },
  {
    id: "a6",
    agentId: "hemera",
    agentName: "HEMERA",
    agentEmoji: "\u{2600}\uFE0F",
    action: "Lead research complete",
    detail: "Enriched 45 new leads with LinkedIn data, company info, and funding stage.",
    timestamp: "2025-02-26T13:30:00Z",
    type: "task",
  },
  {
    id: "a7",
    agentId: "nyx",
    agentName: "NYX",
    agentEmoji: "\u{1F30C}",
    action: "Spawned HEMERA",
    detail: "Agent HEMERA initialized on mac-studio-m2. Loading SOUL.md and skill configs.",
    timestamp: "2025-02-26T09:00:00Z",
    type: "system",
  },
  {
    id: "a8",
    agentId: "nyx",
    agentName: "NYX",
    agentEmoji: "\u{1F30C}",
    action: "System boot",
    detail: "NYX online. Loading guild configuration. Checking agent manifests.",
    timestamp: "2025-02-26T08:55:00Z",
    type: "system",
  },
];

export const tasks: Task[] = [
  {
    id: "t1",
    title: "Process outreach batch 14",
    description: "Send personalized emails to 30 Series A founders from enrichment pipeline",
    agentId: "hemera",
    status: "in-progress",
    priority: "high",
    createdAt: "2025-02-26T14:15:00Z",
    dueDate: "2025-02-26T16:00:00Z",
  },
  {
    id: "t2",
    title: "Follow-up sequence — Week 2",
    description: "Send second touchpoint to 18 leads who opened but didn't reply",
    agentId: "hemera",
    status: "backlog",
    priority: "medium",
    createdAt: "2025-02-26T10:00:00Z",
    dueDate: "2025-02-27T12:00:00Z",
  },
  {
    id: "t3",
    title: "Enrich new lead batch",
    description: "Research and enrich 50 new leads with LinkedIn, funding, and tech stack data",
    agentId: "hemera",
    status: "backlog",
    priority: "medium",
    createdAt: "2025-02-26T09:00:00Z",
    dueDate: null,
  },
  {
    id: "t4",
    title: "Coordinate daily briefing",
    description: "Compile agent activity, task progress, and key metrics for daily summary",
    agentId: "nyx",
    status: "in-progress",
    priority: "high",
    createdAt: "2025-02-26T13:45:00Z",
    dueDate: "2025-02-26T14:30:00Z",
  },
  {
    id: "t5",
    title: "Review agent health metrics",
    description: "Check memory usage, response latency, and error rates for all agents",
    agentId: "nyx",
    status: "done",
    priority: "medium",
    createdAt: "2025-02-26T12:00:00Z",
    dueDate: null,
  },
  {
    id: "t6",
    title: "Update task priority matrix",
    description: "Re-evaluate task priorities based on calendar events and deadlines",
    agentId: "nyx",
    status: "done",
    priority: "low",
    createdAt: "2025-02-26T11:00:00Z",
    dueDate: null,
  },
  {
    id: "t7",
    title: "Draft investor outreach templates",
    description: "Create 3 new email templates for pre-seed investor outreach campaign",
    agentId: "hemera",
    status: "review",
    priority: "high",
    createdAt: "2025-02-25T16:00:00Z",
    dueDate: "2025-02-26T18:00:00Z",
  },
  {
    id: "t8",
    title: "Configure error recovery protocol",
    description: "Set up automatic retry and fallback procedures for failed agent tasks",
    agentId: "nyx",
    status: "backlog",
    priority: "low",
    createdAt: "2025-02-25T10:00:00Z",
    dueDate: null,
  },
];

export const usageData: UsageData[] = [
  { date: "Feb 20", tokensUsed: 145000, apiCalls: 89, cost: 2.31 },
  { date: "Feb 21", tokensUsed: 210000, apiCalls: 134, cost: 3.52 },
  { date: "Feb 22", tokensUsed: 178000, apiCalls: 112, cost: 2.94 },
  { date: "Feb 23", tokensUsed: 95000, apiCalls: 56, cost: 1.48 },
  { date: "Feb 24", tokensUsed: 267000, apiCalls: 178, cost: 4.21 },
  { date: "Feb 25", tokensUsed: 312000, apiCalls: 203, cost: 5.07 },
  { date: "Feb 26", tokensUsed: 189000, apiCalls: 127, cost: 3.12 },
];
