import {
  Agent,
  ActivityEntry,
  Task,
  AgentUsageDay,
  Team,
  CommMessage,
  HITLItem,
  AgentCostEntry,
  TaskChain,
} from "./types";

export const agents: Agent[] = [
  {
    id: "nyx",
    name: "NYX",
    emoji: "\u{1F703}",
    status: "active",
    role: "Lead Agent / Orchestrator",
    description:
      "Sharp, loyal, mischievous. Named after the Greek goddess of night.",
    machine: "MacBook Pro",
    gateway: "localhost",
    model: "claude-opus-4-6",
    currentTask:
      "Manage OWSH operations, FB outreach orchestration, project builds",
    lastActivity: "Just now",
    skills: [
      "Web Search",
      "Browser Control",
      "File Management",
      "Code Generation",
      "WhatsApp Messaging",
      "Telegram Messaging",
      "Email (IMAP)",
      "Calendar",
      "Memory System",
      "Sub-Agent Spawning",
      "GitHub",
      "Vercel Deploy",
    ],
    color: "#7c3aed",
    accentColor: "#a78bfa",
    uptimeSince: "2026-02-02",
  },
  {
    id: "hemera",
    name: "HEMERA",
    emoji: "\u{2600}\uFE0F",
    status: "idle",
    role: "Outreach Operator",
    description:
      "Quiet, precise, patient. Named after the Greek goddess of day. NYX\u2019s first child.",
    machine: "LOKI PC (Win 11, i7-9700F, RTX 2060S)",
    gateway: "remote (not connected)",
    model: "gpt-4o-mini (pending switch)",
    currentTask: "105 prospects in outreach queue (pending deployment)",
    lastActivity: "Today",
    skills: [
      "FB Messenger Outreach",
      "Browser Relay",
      "Message Queue",
      "Status Reporting",
    ],
    color: "#d97706",
    accentColor: "#fbbf24",
    uptimeSince: "2026-02-26",
  },
];

export const activityFeed: ActivityEntry[] = [
  {
    id: "a1",
    agentId: "nyx",
    agentName: "NYX",
    agentEmoji: "\u{1F703}",
    action: "Built The Guild dashboard",
    detail:
      "Deployed The Guild v0.1 \u2014 full dashboard with pixel office, agent management, and task kanban.",
    timestamp: "2026-02-26T15:30:00Z",
    type: "task",
  },
  {
    id: "a2",
    agentId: "nyx",
    agentName: "NYX",
    agentEmoji: "\u{1F703}",
    action: "Sent 11 FB outreach DMs",
    detail:
      "Completed batch outreach to 11 prospects via Facebook Messenger. 9 delivered, 2 failed.",
    timestamp: "2026-02-26T14:15:00Z",
    type: "communication",
  },
  {
    id: "a3",
    agentId: "nyx",
    agentName: "NYX",
    agentEmoji: "\u{1F703}",
    action: "Managed HEMERA setup",
    detail:
      "Initialized HEMERA gateway on LOKI PC. Created identity files and SOUL.md.",
    timestamp: "2026-02-26T12:45:00Z",
    type: "system",
  },
  {
    id: "a4",
    agentId: "hemera",
    agentName: "HEMERA",
    agentEmoji: "\u{2600}\uFE0F",
    action: "Gateway initialized",
    detail:
      "OpenClaw gateway process started on LOKI PC. Awaiting model configuration.",
    timestamp: "2026-02-26T12:30:00Z",
    type: "system",
  },
  {
    id: "a5",
    agentId: "hemera",
    agentName: "HEMERA",
    agentEmoji: "\u{2600}\uFE0F",
    action: "Identity files created",
    detail:
      "SOUL.md and skill configurations generated. Awaiting model switch from gpt-4o-mini.",
    timestamp: "2026-02-26T12:35:00Z",
    type: "system",
  },
  {
    id: "a6",
    agentId: "nyx",
    agentName: "NYX",
    agentEmoji: "\u{1F703}",
    action: "Built Forge v0.1",
    detail:
      "Completed Forge build system \u2014 project scaffolding, template engine, and deployment pipeline.",
    timestamp: "2026-02-26T11:00:00Z",
    type: "task",
  },
  {
    id: "a7",
    agentId: "nyx",
    agentName: "NYX",
    agentEmoji: "\u{1F703}",
    action: "Checked emails",
    detail:
      "Processed inbox via IMAP. 3 new messages, 1 requiring action. Forwarded summary to admin.",
    timestamp: "2026-02-26T09:30:00Z",
    type: "task",
  },
  {
    id: "a8",
    agentId: "nyx",
    agentName: "NYX",
    agentEmoji: "\u{1F703}",
    action: "Verified prospects",
    detail:
      "Cross-referenced 15 outreach prospects against LinkedIn and company databases. 12 verified.",
    timestamp: "2026-02-26T08:45:00Z",
    type: "task",
  },
  {
    id: "a9",
    agentId: "hemera",
    agentName: "HEMERA",
    agentEmoji: "\u{2600}\uFE0F",
    action: "Awaiting model switch",
    detail:
      "Current model: gpt-4o-mini. Pending switch to claude-sonnet-4-5 for improved outreach quality.",
    timestamp: "2026-02-26T12:40:00Z",
    type: "system",
  },
];

export const tasks: Task[] = [
  {
    id: "t1",
    title: "The Guild v0.1 build",
    description:
      "Build the full Guild dashboard with pixel office, agent management, activity feed, and task kanban",
    agentId: "nyx",
    status: "completed",
    priority: "high",
    createdAt: "2026-02-25T10:00:00Z",
    dueDate: "2026-02-26T18:00:00Z",
  },
  {
    id: "t2",
    title: "Forge v0.1",
    description:
      "Build Forge scaffolding system \u2014 project templates, build pipeline, and deployment automation",
    agentId: "nyx",
    status: "completed",
    priority: "high",
    createdAt: "2026-02-24T08:00:00Z",
    dueDate: "2026-02-26T12:00:00Z",
  },
  {
    id: "t3",
    title: "Wire Guild to gateway",
    description:
      "Connect The Guild dashboard to OpenClaw gateway for live agent data, status, and task sync",
    agentId: "nyx",
    status: "in-progress",
    priority: "high",
    createdAt: "2026-02-26T14:00:00Z",
    dueDate: null,
  },
  {
    id: "t4",
    title: "HEMERA deployment",
    description:
      "Complete HEMERA agent deployment on LOKI PC \u2014 model switch, skill configs, and gateway connection",
    agentId: "nyx",
    status: "blocked",
    priority: "high",
    createdAt: "2026-02-26T12:00:00Z",
    dueDate: null,
  },
  {
    id: "t5",
    title: "Studio launch prep 3/3",
    description:
      "Final preparation for OWSH Studio launch \u2014 branding assets, landing page, and deployment",
    agentId: "nyx",
    status: "upcoming",
    priority: "medium",
    createdAt: "2026-02-26T08:00:00Z",
    dueDate: "2026-03-03T00:00:00Z",
  },
  {
    id: "t6",
    title: "Process outreach queue \u2014 105 prospects",
    description:
      "Execute Facebook Messenger outreach to 105 prospects in queue. Personalize messages and handle responses.",
    agentId: "hemera",
    status: "pending",
    priority: "high",
    createdAt: "2026-02-26T12:00:00Z",
    dueDate: null,
  },
  {
    id: "t7",
    title: "Send batch 1 retry \u2014 9 failed DMs",
    description:
      "Retry 9 failed Facebook DMs from initial outreach batch. Diagnose delivery failures.",
    agentId: "hemera",
    status: "pending",
    priority: "medium",
    createdAt: "2026-02-26T14:00:00Z",
    dueDate: null,
  },
  {
    id: "t8",
    title: "Daily outreach execution",
    description:
      "Recurring daily task: process outreach queue, send personalized DMs, log results, report status via Telegram.",
    agentId: "hemera",
    status: "recurring",
    priority: "medium",
    createdAt: "2026-02-26T08:00:00Z",
    dueDate: null,
  },
];

export const dailyUsage: AgentUsageDay[] = [
  { date: "Feb 13", nyx: 45200, hemera: 0 },
  { date: "Feb 14", nyx: 52100, hemera: 0 },
  { date: "Feb 15", nyx: 38400, hemera: 0 },
  { date: "Feb 16", nyx: 29800, hemera: 0 },
  { date: "Feb 17", nyx: 61300, hemera: 0 },
  { date: "Feb 18", nyx: 47600, hemera: 0 },
  { date: "Feb 19", nyx: 55100, hemera: 0 },
  { date: "Feb 20", nyx: 43700, hemera: 0 },
  { date: "Feb 21", nyx: 68200, hemera: 0 },
  { date: "Feb 22", nyx: 51400, hemera: 0 },
  { date: "Feb 23", nyx: 35900, hemera: 0 },
  { date: "Feb 24", nyx: 58300, hemera: 0 },
  { date: "Feb 25", nyx: 72100, hemera: 0 },
  { date: "Feb 26", nyx: 48500, hemera: 3200 },
];

export const mockTeams: Team[] = [
  {
    id: "ops",
    name: "Operations",
    description: "Core operations team handling outreach, builds, and daily ops",
    color: "#7c3aed",
    leadAgentId: "nyx",
    memberAgentIds: ["nyx", "hemera"],
    createdAt: "2026-02-26T00:00:00Z",
    icon: "shield",
  },
];

export const mockComms: CommMessage[] = [
  {
    id: "comm-1",
    timestamp: "2026-02-26T15:30:00Z",
    fromAgentId: "nyx",
    toAgentId: "hemera",
    channel: "session",
    direction: "nyx-to-hemera",
    content: "HEMERA, your gateway is initialized. I've pushed the SOUL.md and skill configs. Standing by for model switch confirmation.",
    contentPreview: "Gateway initialized, standing by for model switch...",
    deliveryStatus: "delivered",
  },
  {
    id: "comm-2",
    timestamp: "2026-02-26T15:32:00Z",
    fromAgentId: "hemera",
    toAgentId: "nyx",
    channel: "session",
    direction: "hemera-to-nyx",
    content: "Received. Identity files verified. Current model: gpt-4o-mini. Awaiting switch to claude-sonnet-4-5.",
    contentPreview: "Identity verified, awaiting model switch...",
    deliveryStatus: "delivered",
  },
  {
    id: "comm-3",
    timestamp: "2026-02-26T14:00:00Z",
    fromAgentId: "nyx",
    toAgentId: "noah",
    channel: "alert-file",
    direction: "nyx-to-noah",
    content: "Outreach batch 1 complete. 9/11 DMs delivered successfully. 2 failed due to account restrictions. Retrying in next batch.",
    contentPreview: "Outreach batch 1: 9/11 delivered, 2 failed...",
    deliveryStatus: "delivered",
  },
  {
    id: "comm-4",
    timestamp: "2026-02-26T13:45:00Z",
    fromAgentId: "hemera",
    toAgentId: "noah",
    channel: "delivery-queue",
    direction: "hemera-to-noah",
    content: "105 prospects loaded into outreach queue. Ready to begin processing once deployment is confirmed.",
    contentPreview: "105 prospects loaded, awaiting deployment...",
    deliveryStatus: "delivered",
  },
  {
    id: "comm-5",
    timestamp: "2026-02-26T12:00:00Z",
    fromAgentId: "nyx",
    toAgentId: "hemera",
    channel: "git-sync",
    direction: "nyx-to-hemera",
    content: "Synced latest prospect list and outreach templates to shared workspace. 15 new prospects verified and added.",
    contentPreview: "Synced prospect list, 15 new verified...",
    deliveryStatus: "delivered",
  },
];

export const mockHITLItems: HITLItem[] = [
  {
    id: "hitl-mock-1",
    type: "approval",
    title: "Deploy production build to Vercel",
    description: "NYX is ready to deploy the latest build to production. This will affect the live site.",
    agentId: "nyx",
    agentName: "NYX",
    agentEmoji: "\u{1F703}",
    priority: "critical",
    status: "pending",
    createdAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    context: "Build completed successfully with 0 errors. All tests passing. Ready for production deployment.",
    sessionId: "mock-session-1",
  },
  {
    id: "hitl-mock-2",
    type: "decision",
    title: "Choose outreach message template",
    description: "HEMERA needs a decision on which template to use for the next batch of 50 outreach messages.",
    agentId: "hemera",
    agentName: "HEMERA",
    agentEmoji: "\u2600\uFE0F",
    priority: "high",
    status: "pending",
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    context: "Template A: Professional intro. Template B: Casual opener. Template C: Referral-based warm intro.",
    sessionId: "mock-session-2",
  },
  {
    id: "hitl-mock-3",
    type: "review",
    title: "Review generated email content",
    description: "NYX drafted a follow-up email to a prospect. Needs human review before sending.",
    agentId: "nyx",
    agentName: "NYX",
    agentEmoji: "\u{1F703}",
    priority: "medium",
    status: "pending",
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    context: "Subject: Quick follow-up on your website audit. Body: Hi [Name], I wanted to follow up...",
    sessionId: "mock-session-3",
    detectedPattern: "need your approval",
  },
];

export const mockCostEntries: AgentCostEntry[] = [
  { date: "Feb 20", agentId: "nyx", inputTokens: 26220, outputTokens: 17480, totalTokens: 43700, estimatedCost: 1.70, model: "claude-opus-4-6", sessionCount: 3 },
  { date: "Feb 21", agentId: "nyx", inputTokens: 40920, outputTokens: 27280, totalTokens: 68200, estimatedCost: 2.66, model: "claude-opus-4-6", sessionCount: 5 },
  { date: "Feb 22", agentId: "nyx", inputTokens: 30840, outputTokens: 20560, totalTokens: 51400, estimatedCost: 2.00, model: "claude-opus-4-6", sessionCount: 3 },
  { date: "Feb 23", agentId: "nyx", inputTokens: 21540, outputTokens: 14360, totalTokens: 35900, estimatedCost: 1.40, model: "claude-opus-4-6", sessionCount: 2 },
  { date: "Feb 24", agentId: "nyx", inputTokens: 34980, outputTokens: 23320, totalTokens: 58300, estimatedCost: 2.27, model: "claude-opus-4-6", sessionCount: 4 },
  { date: "Feb 25", agentId: "nyx", inputTokens: 43260, outputTokens: 28840, totalTokens: 72100, estimatedCost: 2.81, model: "claude-opus-4-6", sessionCount: 5 },
  { date: "Feb 26", agentId: "nyx", inputTokens: 29100, outputTokens: 19400, totalTokens: 48500, estimatedCost: 1.89, model: "claude-opus-4-6", sessionCount: 3 },
];

export const mockChains: TaskChain[] = [
  {
    id: "chain-outreach-1",
    name: "Daily Outreach Pipeline",
    description: "Automated pipeline: check prospects, send DMs, report results",
    status: "active",
    steps: [
      {
        id: "step-outreach-1",
        order: 0,
        name: "Check prospects",
        trigger: { type: "manual" },
        action: { type: "start-task", agentId: "nyx", taskTitle: "Check prospect queue", taskDescription: "Review and validate outreach prospect list" },
        status: "completed",
        startedAt: "2026-02-26T08:00:00Z",
        completedAt: "2026-02-26T08:15:00Z",
        onFailure: "stop",
        maxRetries: 0,
        retryCount: 0,
      },
      {
        id: "step-outreach-2",
        order: 1,
        name: "Send DMs",
        trigger: { type: "task-complete", taskId: "t6" },
        action: { type: "start-task", agentId: "hemera", taskTitle: "Send outreach DMs", taskDescription: "Process and send personalized DMs to verified prospects" },
        status: "active",
        startedAt: "2026-02-26T08:16:00Z",
        onFailure: "retry",
        maxRetries: 2,
        retryCount: 0,
      },
      {
        id: "step-outreach-3",
        order: 2,
        name: "Report results",
        trigger: { type: "task-complete" },
        action: { type: "notify-human", message: "Outreach batch complete. Check results dashboard." },
        status: "pending",
        onFailure: "skip",
        maxRetries: 0,
        retryCount: 0,
      },
    ],
    createdAt: "2026-02-25T10:00:00Z",
    lastRunAt: "2026-02-26T08:16:00Z",
    isTemplate: false,
  },
  {
    id: "chain-template-deploy",
    name: "Deploy and Verify",
    description: "Template: Run tests, build, deploy, and health check",
    status: "draft",
    steps: [
      {
        id: "step-deploy-1",
        order: 0,
        name: "Run tests",
        trigger: { type: "manual" },
        action: { type: "start-task", agentId: "nyx", taskTitle: "Run test suite", taskDescription: "Execute all tests" },
        status: "pending",
        onFailure: "stop",
        maxRetries: 0,
        retryCount: 0,
      },
      {
        id: "step-deploy-2",
        order: 1,
        name: "Build project",
        trigger: { type: "task-complete" },
        action: { type: "start-task", agentId: "nyx", taskTitle: "Build production", taskDescription: "Create production build" },
        status: "pending",
        onFailure: "stop",
        maxRetries: 0,
        retryCount: 0,
      },
      {
        id: "step-deploy-3",
        order: 2,
        name: "Deploy",
        trigger: { type: "task-complete" },
        action: { type: "webhook", webhookUrl: "https://api.vercel.com/v1/deploy" },
        status: "pending",
        onFailure: "stop",
        maxRetries: 0,
        retryCount: 0,
      },
      {
        id: "step-deploy-4",
        order: 3,
        name: "Health check",
        trigger: { type: "time-based", cronExpression: "2" },
        action: { type: "start-task", agentId: "nyx", taskTitle: "Health check", taskDescription: "Verify deployment is healthy" },
        status: "pending",
        onFailure: "retry",
        maxRetries: 3,
        retryCount: 0,
      },
    ],
    createdAt: "2026-02-24T10:00:00Z",
    isTemplate: true,
  },
];
